"""Independent frozen reactions, provenance and unchanged Controller integration."""
from copy import deepcopy
from fractions import Fraction
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

from core import ToolResult,ToolValidationError
from core.persistence import write_json
from tools.floor.design_tool import FloorDesignTool
from tools.floor.design_store import FloorDesignStore
from tools.floor.design_adapter import canonical_hash
from tools.floor.reaction_calculation import beam_reactions,wall_weight
from tools.floor.reaction_input import validate_parameters
from tools.floor.reaction_adapter import FloorReactionAdapter
from tools.floor.reaction_tools import FloorReactionTool
from examples.floor_reactions import run_request

ROOT=Path(__file__).resolve().parents[1]
REF=json.loads((ROOT/'tests/fixtures/floor_reaction_references.json').read_text(encoding='utf-8'))


def parameters(ref):
    return {'design_result_ref':ref,'beam_binding':{'member_id':'MB-1','support_ids':['S1','S2','S3','S4'],
        'coordinate_system':'legacy_main_beam_calculation_supports_mm','source':'Anonymous teaching support map'},
        'scope':{'purpose':'teaching','beam_model':'legacy_main_beam_constant_EI','baseline_wall_loads_excluded':True,
            'baseline_exclusion_source':'Fixed walls excluded from original load record',
            'global_frame_analysis':False,'support_vertical_constraint':'bilateral_no_settlement','wall_stiffness_ignored':True}}


def wall():
    return {'wall_id':'W1','member_id':'MB-1','start_mm':1000,'end_mm':5000,'height_mm':3000,
        'thickness_mm':200,'density_kN_m3':8,'fixed':True,'non_load_bearing':True,'direct_on_beam':True,
        'centred_on_beam':True,'weight_basis':'characteristic','load_model':'uniform_equivalent_over_wall_length',
        'openings':[{'opening_id':'O1','x_local_mm':1000,'bottom_mm':0,'width_mm':1000,'height_mm':2000}],
        'finishes':[{'side':side,'thickness_mm':15,'density_kN_m3':20} for side in ('left','right')],
        'additional_weight_kN':2,'source':{'load_record_id':'WR1','description':'Anonymous fixed infill wall',
            'geometry_source':'Teaching dimensions','density_source':'Declared teaching value 8 kN/m3',
            'finish_source':'Two explicit finishes','additional_weight_source':'Explicit teaching 2 kN allowance'}}


class ReactionKernelTests(unittest.TestCase):
    def test_independent_uniform_partial_and_cross_support_references(self):
        for key in ('full_udl','partial_first','cross_support'):
            case=REF[key]
            result=beam_reactions(REF['spans_m'],udls=[(case['start_m'],case['end_m'],case['q_kN_m'])])
            self.assertEqual(result['reactions'],list(map(Fraction,case['reactions'])),key)
            self.assertEqual(result['force_residual'],0);self.assertEqual(result['moment_residual'],0)
            mirror=beam_reactions([6,6,6],udls=[(18-case['end_m'],18-case['start_m'],10)])
            self.assertEqual(mirror['reactions'],list(reversed(result['reactions'])))

    def test_single_span_and_old_third_points_independent(self):
        self.assertEqual(beam_reactions([6],udls=[(0,6,10)])['reactions'],[30,30])
        self.assertEqual(beam_reactions([6,6,6],[(x,10) for x in (2,4,8,10,14,16)])['reactions'],
                         list(map(Fraction,REF['third_points']['reactions'])))
        # Independent three-moment basis vectors, not generated by tested kernel.
        bases=[[37,63,-12,2],[-6,51,51,-6],[2,-12,63,37]]
        for i,row in enumerate(bases):
            self.assertEqual(beam_reactions([6,6,6],[(6*i+2,1),(6*i+4,1)])['reactions'],
                             [Fraction(v,45) for v in row])

    def test_point_at_support_and_kernel_invalid_inputs(self):
        self.assertEqual(beam_reactions([6,6,6],[(6,10)])['reactions'],[0,10,0,0])
        for spans,points,udls in [([True],[],[]),([float('nan')],[],[]),([0],[],[]),([6],[(7,1)],[]),([6],[],[(2,1,4)]),([6],[],[(0,6,-1)])]:
            with self.assertRaises(ValueError): beam_reactions(spans,points,udls)

    def test_wall_weight_frozen_reference_and_single_factoring(self):
        w=wall();w['openings']=[];w['additional_weight_kN']=0
        self.assertEqual(wall_weight(w,1.3)['characteristic_weight_kN']['exact'],'132/5')
        w['openings']=wall()['openings']
        self.assertEqual(wall_weight(w,1.3)['characteristic_weight_kN']['value'],22)
        w['additional_weight_kN']=2
        result=wall_weight(w,1.3)
        self.assertEqual(result['characteristic_weight_kN']['value'],24)
        self.assertEqual(result['design_weight_kN']['value'],31.2)
        self.assertEqual(result['design_q_kN_m']['exact'],'39/5')

    def test_wall_cross_field_rejection_and_explicit_boolean_scope(self):
        base=parameters('floor-'+'a'*32);base['walls']=[wall()]
        validate_parameters(base,walls=True)
        mutations=[lambda p:p['walls'][0].update(height_mm=True),
            lambda p:p['walls'][0].update(density_kN_m3=float('inf')),
            lambda p:p['scope'].update(baseline_wall_loads_excluded=1),
            lambda p:p['scope'].update(wall_stiffness_ignored=False),
            lambda p:p['walls'][0].update(member_id='other'),
            lambda p:p['walls'][0].update(end_mm=500),
            lambda p:p['walls'][0]['openings'][0].update(width_mm=5000),
            lambda p:p['walls'][0]['openings'].append({**wall()['openings'][0],'opening_id':'O2'}),
            lambda p:p['walls'][0]['finishes'].append(wall()['finishes'][0]),
            lambda p:p['walls'].append(wall()),
            lambda p:p['walls'][0]['source'].update(density_source=' '),
            lambda p:p['beam_binding'].update(coordinate_system='axis_grid'),
            lambda p:p['walls'][0].update(extra=1),
            lambda p:p['beam_binding'].update(support_ids=['S1']*4)]
        for mutation in mutations:
            p=deepcopy(base);mutation(p)
            with self.subTest(mutation=mutation),self.assertRaises(ToolValidationError): validate_parameters(p,walls=True)
        p=deepcopy(base);p['walls'][0]['openings'].append({'opening_id':'O2','x_local_mm':2000,'bottom_mm':0,'width_mm':1000,'height_mm':2000})
        validate_parameters(p,walls=True) # Touching is allowed, overlap is not.


class ReactionIntegrationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.temp=tempfile.TemporaryDirectory(prefix='reaction_source_');cls.root=Path(cls.temp.name)
        cls.store=FloorDesignStore(cls.root/'designs')
        cls.design=FloorDesignTool(store=cls.store).execute({'project_id':'REACTION-TEST','tool':'design_floor_system',
            'context':{'unit_system':'SI','design_code':'GB'},'parameters':{'input_mode':'template',
                'template_id':'office_floor_demo_v1','span_x':6000,'span_y':6000,'concrete':'C30','steel':'HRB400','live_load':2}})
        if not cls.design.success: raise AssertionError(cls.design.errors)
        cls.ref=cls.design.metadata['design_result_ref']

    @classmethod
    def tearDownClass(cls): cls.temp.cleanup()

    def setUp(self):
        self.temp_case=tempfile.TemporaryDirectory();self.addCleanup(self.temp_case.cleanup)
        self.results=Path(self.temp_case.name)
        self.tool=FloorReactionTool(self.store,self.results,walls=True)
        self.p=parameters(self.ref);self.p['walls']=[wall()]
        self.env={'project_id':'REACTION-TEST','tool':self.tool.name,'context':{'unit_system':'SI','design_code':'GB'},'parameters':self.p}

    def test_all_patterns_superposition_immutable_source_and_controls(self):
        before=(self.root/'designs'/(self.ref+'.json')).read_bytes()
        result=self.tool.execute(self.env);self.assertTrue(result.success,result.errors)
        self.assertEqual(result.result['status'],'MODEL_ANALYZED')
        self.assertFalse(result.result['column_input_ready']);self.assertTrue(result.result['floor_design_recheck_required'])
        self.assertEqual(len(result.result['cases']),8)
        for c in result.result['cases']:
            for b,w,t in zip(c['baseline_reactions_kN'],c['wall_increment_reactions_kN'],c['total_reactions_kN']):
                self.assertEqual(Fraction(b['exact'])+Fraction(w['exact']),Fraction(t['exact']))
            self.assertEqual(c['force_residual_kN']['exact'],'0');self.assertEqual(c['moment_residual_kN_m']['exact'],'0')
        for j,control in enumerate(result.result['controls']):
            vals={c['pattern']:Fraction(c['total_reactions_kN'][j]['exact']) for c in result.result['cases']}
            self.assertEqual(control['maximum_patterns'],[p for p,v in vals.items() if v==max(vals.values())])
        self.assertEqual(before,(self.root/'designs'/(self.ref+'.json')).read_bytes())
        loaded=self.tool.store.load(result.metadata['reaction_result_ref'],project_id='REACTION-TEST')
        self.assertEqual(loaded.result,result.result)
        with self.assertRaises(ValueError):self.tool.store.load(result.metadata['reaction_result_ref'],project_id='OTHER')
        self.assertNotEqual(self.tool.execute(self.env).metadata['reaction_result_ref'],result.metadata['reaction_result_ref'])

    def test_extraction_and_wrong_project_coordinate_or_unit(self):
        extract=FloorReactionTool(self.store,self.results)
        env={**self.env,'tool':extract.name,'parameters':parameters(self.ref)}
        result=extract.execute(env);self.assertTrue(result.success,result.errors)
        self.assertFalse(result.result['floor_design_recheck_required'])
        for c in result.result['cases']:
            self.assertTrue(all(v['exact']=='0' for v in c['wall_increment_reactions_kN']))
        for field,value in [('project_id','OTHER'),('context',{'unit_system':'US','design_code':'GB'})]:
            self.assertFalse(self.tool.execute({**self.env,field:value}).success)
        p=deepcopy(self.p);p['walls'][0]['end_mm']=20000
        self.assertFalse(self.tool.execute({**self.env,'parameters':p}).success)

    def test_rehashed_legacy_wrong_load_reaction_pattern_or_segment_rejected(self):
        for mutate in [lambda raw:raw['loads'].update(G_kN=1),
            lambda raw:raw['envelope']['cases'][0]['reactions'].__setitem__(0,1),
            lambda raw:raw['envelope']['cases'][0].update(pattern='111'),
            lambda raw:raw['envelope']['cases'][0]['segments'][0].update(m0=1),
            lambda raw:raw['spans']['main_m'].__setitem__(0,6)]:
            data=self.design.to_dict();mutate(data['result']['legacy_result'])
            data['metadata']['legacy_result_sha256']=canonical_hash(data['result']['legacy_result'])
            forged=self.store.save(ToolResult(**data))
            p=deepcopy(self.p);p['design_result_ref']=forged
            self.assertFalse(self.tool.execute({**self.env,'parameters':p}).success)

    def test_rehashed_reaction_semantic_tamper_rejected(self):
        result=self.tool.execute(self.env);self.assertTrue(result.success,result.errors)
        path=self.results/(result.metadata['reaction_result_ref']+'.json')
        payload=json.loads(path.read_text(encoding='utf-8'))
        payload['reaction']['result']['cases'][0]['total_reactions_kN'][0]={'value':1,'exact':'1'}
        payload['checksum']=canonical_hash(payload['reaction']);write_json(path,payload)
        with self.assertRaises(ValueError):self.tool.store.load(result.metadata['reaction_result_ref'],project_id='REACTION-TEST')

    def test_negative_increment_is_preserved_and_total_contact_flag_is_separate(self):
        result=self.tool.execute(self.env);self.assertTrue(result.success,result.errors)
        self.assertTrue(any(Fraction(v['exact'])<0 for v in result.result['cases'][0]['wall_increment_reactions_kN']))
        self.assertFalse(result.result['support_contact_review_required'])
        p=deepcopy(self.p);p['walls'][0]['density_kN_m3']=1000
        high=self.tool.execute({**self.env,'parameters':p});self.assertTrue(high.success,high.errors)
        self.assertTrue(high.result['support_contact_review_required'])
        self.assertTrue(any(Fraction(v['exact'])<0 for c in high.result['cases'] for v in c['total_reactions_kN']))

    def test_missing_source_or_failed_storage_never_claims_success(self):
        p=deepcopy(self.p);p['design_result_ref']='floor-'+'f'*32
        self.assertFalse(self.tool.execute({**self.env,'parameters':p}).success)
        with patch.object(self.tool.store,'save',side_effect=OSError('disk failure')):
            result=self.tool.execute(self.env)
        self.assertFalse(result.success);self.assertNotIn('reaction_result_ref',result.metadata)

    def test_generic_controller_cli_and_failed_validation_stop(self):
        result=run_request(self.env,self.root);self.assertTrue(result['success'],result['errors'])
        self.assertEqual([c['tool'] for c in result['tool_calls']],['analyze_floor_wall_reactions'])
        p=deepcopy(self.p);p['walls'][0]['height_mm']=True
        failed=run_request({**self.env,'parameters':p},self.root)
        self.assertFalse(failed['success']);self.assertEqual(failed['tool_calls'],[])
        path=self.results/'request.json';write_json(path,self.env)
        proc=subprocess.run([sys.executable,'-m','examples.floor_reactions','--request-file',str(path),
            '--output-root',str(self.root)],cwd=ROOT,capture_output=True,timeout=90)
        self.assertEqual(proc.returncode,0,proc.stderr);self.assertTrue(json.loads(proc.stdout)['success'])
