"""Frozen hand references, actual geometry/restraint and result integrity."""
from copy import deepcopy
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

from core import ToolValidationError
from core.plugin_base import PluginContext
from core.plugin_loader import load_plugins
from examples.column_layouts import run_request
from tests.test_column_combinations import combination_parameters
from tests.test_column_tools import envelope
from tools.column.json_data import canonical_hash
from tools.column.layout_calculation import (candidate_actual, candidate_sequence, check_column_layouts,
    design_column_layouts, validate_design_semantics)
from tools.column.layout_input import validate_actual, validate_parameters
from tools.column.layout_store import ColumnLayoutStore, ColumnLayoutReferenceError
from tools.column.layout_tools import ColumnLayoutCheckTool, ColumnLayoutDesignTool

ROOT = Path(__file__).resolve().parents[1]


def parameters(b=500, h=500, force=3500, layouts=None):
    data = combination_parameters(forces=[force, force])
    data['model']['section'].update(b_mm=b, h_mm=h, cover_to_outer_tie_mm=25)
    data['model']['effective_length']['l0_mm'] = 2400
    data['model']['ties'] = {'diameter_mm': 8, 'spacing_mm': 150, 'hook_angle_deg': 135, 'hook_extension_mm': 80}
    data['layout_candidates'] = layouts or ['four_corner_bars', 'six_b', 'six_h', 'eight_perimeter']
    return data


class LayoutCalculationTests(unittest.TestCase):
    def test_independent_frozen_references_all_layouts_and_weak_actual(self):
        # These constants were frozen in f460dc6 before the implementation,
        # independently calculated and reviewed; never generated by this module.
        references = [(300, 300, 'four_corner_bars', 16, 1300, 804, 402, 402, 218, 218, 1418.796, 'PASS'),
            (500, 300, 'six_b', 16, 2000, 1206, 603, 402, 209, 218, 2321.244, 'PASS'),
            (300, 500, 'six_h', 16, 2000, 1206, 402, 603, 218, 209, 2321.244, 'PASS'),
            (500, 500, 'eight_perimeter', 16, 3500, 1608, 603, 603, 209, 209, 3738.492, 'PASS'),
            (500, 500, 'eight_perimeter', 14, 3500, 1231, 461, 461, 210, 210, 3616.344, 'FAIL')]
        for b, h, layout, dia, n, steel, ab, ah, sb, sh, capacity, status in references:
            with self.subTest(layout=layout, dia=dia):
                p = parameters(b, h, n)
                before = deepcopy(p)
                actual = candidate_actual(layout, dia)
                report = check_column_layouts(p, actual)
                self.assertEqual(report['status'], status)
                self.assertEqual(report['actual'], actual)
                self.assertEqual(report['controlling_combination_ids'], ['ULS-1', 'ULS-2'])
                for group in report['combination_results']:
                    r = group['report']
                    self.assertEqual(r['intermediates']['total_area_mm2'], steel)
                    self.assertAlmostEqual(r['intermediates']['Nu_kN'], capacity, delta=1e-6)
                    for face in r['faces']:
                        expected_area, spacing = (ab, sb) if face['face'].startswith('b') else (ah, sh)
                        self.assertEqual(face['area_mm2'], expected_area)
                        for segment in face['segments']:
                            self.assertEqual(segment['center_mm'], spacing)
                            self.assertEqual(segment['clear_mm'], spacing - dia)
                    self.assertEqual(len(r['bars']), actual['bar_count'])
                self.assertEqual(p, before)

    def test_all_literal_area_columns_and_geometry(self):
        expected = {12: (452, 678, 904), 14: (615, 923, 1231), 16: (804, 1206, 1608),
            18: (1017, 1527, 2036), 20: (1256, 1884, 2513), 22: (1520, 2281, 3041),
            25: (1964, 2945, 3927), 28: (2463, 3695, 4926)}
        for dia, areas in expected.items():
            for layout, area in zip(('four_corner_bars', 'six_b', 'eight_perimeter'), areas):
                r = check_column_layouts(parameters(), candidate_actual(layout, dia))['combination_results'][0]['report']
                self.assertEqual(r['intermediates']['total_area_mm2'], area)
                self.assertEqual(len({(v['x_mm'], v['y_mm']) for v in r['bars']}), r['actual']['bar_count'])

    def test_candidate_authorization_area_order_and_fixed_input(self):
        p = parameters()
        before = deepcopy(p)
        report = design_column_layouts(p)
        self.assertEqual(report['selected']['actual'], candidate_actual('eight_perimeter', 16))
        self.assertEqual([r['actual'] for r in report['attempts']], candidate_sequence(p)[:len(report['attempts'])])
        p['layout_candidates'] = ['six_b']
        failed = design_column_layouts(p)
        self.assertEqual(failed['status'], 'FAIL')
        self.assertEqual(len(failed['attempts']), 8)
        self.assertTrue(all(r['actual']['layout'] == 'six_b' for r in failed['attempts']))
        self.assertEqual(before['model'], p['model'])

    def test_six_directions_and_tie_endpoint_binding(self):
        for b, h, layout, axis, endpoints in [(500, 300, 'six_b', 'h', ['BM', 'TM']),
                (300, 500, 'six_h', 'b', ['LM', 'RM'])]:
            r = check_column_layouts(parameters(b, h, 2000), candidate_actual(layout, 16))
            self.assertEqual(r['status'], 'PASS')
            self.assertEqual(r['combination_results'][0]['report']['required_crossties'],
                [{'axis': axis, 'end_bar_ids': endpoints}])

    def test_slender_layout_uses_original_stability_coefficient(self):
        p = parameters(force=2700)
        p['model']['effective_length']['l0_mm'] = 10000
        report = check_column_layouts(p, candidate_actual('eight_perimeter', 16))
        self.assertEqual(report['status'], 'PASS')
        for row in report['combination_results']:
            self.assertEqual(row['report']['intermediates']['phi'], .75)
            self.assertAlmostEqual(row['report']['intermediates']['Nu_kN'], 2803.869, delta=1e-6)

    def test_control_ids_use_original_force_not_rounded_utilization(self):
        p = parameters()
        p['combinations'][0]['actions']['N_kN'] = 3500.00000000001
        report = check_column_layouts(p, candidate_actual('eight_perimeter', 16))
        self.assertEqual(report['controlling_combination_ids'], ['ULS-1'])

    def test_actual_check_never_designs_and_does_not_repair_restraints(self):
        p = parameters()
        for field, value in [('crosstie_axes', ['b']), ('perimeter_closed', False),
                ('crossties_at_every_layer', False), ('ends_engage_bars', False)]:
            actual = candidate_actual('eight_perimeter', 16)
            actual[field] = value
            with patch('tools.column.layout_calculation.design_column_layouts', side_effect=AssertionError('no design')):
                report = check_column_layouts(p, actual)
            self.assertEqual(report['status'], 'FAIL')
            self.assertEqual(report['actual'], actual)
            self.assertEqual(len(report['combination_results']), 2)

    def test_empty_crosstie_declarations_are_not_applicable_for_four_corners(self):
        actual = candidate_actual('four_corner_bars', 16)
        actual.update(crossties_at_every_layer=False, ends_engage_bars=False)
        r = check_column_layouts(parameters(300, 300, 1300), actual)
        self.assertEqual(r['status'], 'PASS')
        self.assertEqual(r['combination_results'][0]['report']['required_crossties'], [])

    def test_hook_exact_boundary_and_diameter_scaling(self):
        for dt, extension, expected in [(8, 80, 'PASS'), (8, 79.999, 'FAIL'), (10, 99, 'FAIL'), (10, 100, 'PASS')]:
            p = parameters(300, 300, 1300)
            p['model']['ties'].update(diameter_mm=dt, hook_extension_mm=extension)
            self.assertEqual(check_column_layouts(p, candidate_actual('four_corner_bars', 16))['status'], expected)
        p['model']['ties']['hook_angle_deg'] = 180
        self.assertEqual(check_column_layouts(p, candidate_actual('four_corner_bars', 16))['status'], 'FAIL')

    def test_face_center_and_clear_boundaries(self):
        # For 4d16 c25 dt8, full center=b-82: 382 yields exactly300.
        for b, expected in [(382, 'PASS'), (382.001, 'FAIL')]:
            self.assertEqual(check_column_layouts(parameters(b, 300, 1300),
                candidate_actual('four_corner_bars', 16))['status'], expected)
        # Six_b d28 at b300 c25 dt8: split center103, clear75;
        # no fabricated clipping of points or replacement of actual bars.
        r = check_column_layouts(parameters(300, 300, 1300), candidate_actual('six_b', 28))
        self.assertEqual(r['combination_results'][0]['report']['faces'][0]['segments'][0]['clear_mm'], 75)

    def test_new_side_rounding_policy_does_not_modify_legacy(self):
        from tools.column.calculation import check_column
        from tests.test_column_calculation import column_model, actual_bars
        old = check_column(column_model(), actual_bars(14))
        new = check_column_layouts(parameters(300, 300, 1300), candidate_actual('four_corner_bars', 14))
        self.assertEqual(old['intermediates']['side_area_mm2'], 307.5)
        self.assertEqual(new['combination_results'][0]['report']['faces'][0]['area_mm2'], 308)

    def test_failures_capacity_ratio_tie_spacing_and_cover(self):
        for change in ('capacity', 'spacing', 'cover', 'tie_diameter'):
            p = parameters()
            if change == 'capacity':
                p['combinations'][0]['actions']['N_kN'] = 99999
            elif change == 'spacing':
                p['model']['ties']['spacing_mm'] = 401
            elif change == 'cover':
                p['model']['section']['cover_to_outer_tie_mm'] = 1
            else:
                p['model']['ties']['diameter_mm'] = 5
            self.assertEqual(check_column_layouts(p, candidate_actual('eight_perimeter', 28))['status'], 'FAIL')


class LayoutInputTests(unittest.TestCase):
    def test_missing_extra_bool_nonfinite_material_and_scope(self):
        original = parameters()
        variants = []
        p = deepcopy(original); p['model']['ties'].pop('hook_extension_mm'); variants.append(p)
        p = deepcopy(original); p['model']['ties']['configuration'] = 'single_closed_rectangular'; variants.append(p)
        p = deepcopy(original); p['model']['section']['b_mm'] = True; variants.append(p)
        p = deepcopy(original); p['model']['ties']['hook_angle_deg'] = False; variants.append(p)
        p = deepcopy(original); p['combinations'][0]['actions']['N_kN'] = float('inf'); variants.append(p)
        p = deepcopy(original); p['model']['materials']['fc_MPa'] = 99; variants.append(p)
        p = deepcopy(original); p['combinations'][0]['actions']['Mx_kN_m'] = 1; variants.append(p)
        p = deepcopy(original); p['model']['scope']['seismic'] = True; variants.append(p)
        p = deepcopy(original); p['model']['effective_length']['l0_mm'] = 26000; variants.append(p)
        p = deepcopy(original); p['model']['section']['cover_to_outer_tie_mm'] = 50; variants.append(p)
        for p in variants:
            with self.assertRaises(ToolValidationError): validate_parameters(p)
        validate_parameters(original)

    def test_source_layout_and_actual_mismatch(self):
        variants = []
        p = parameters(); p['combinations'][1]['source']['member_id'] = 'OTHER'; variants.append(p)
        p = parameters(); p['combinations'][1]['source']['analysis_id'] = 'OTHER'; variants.append(p)
        p = parameters(); p['combinations'][1]['source']['force_record_id'] = 'ROW-1'; variants.append(p)
        p = parameters(); p['layout_candidates'] = ['six_b', 'six_b']; variants.append(p)
        p = parameters(); p['layout_candidates'] = []; variants.append(p)
        p = parameters(); p['layout_candidates'] = ['unknown']; variants.append(p)
        for p in variants:
            with self.assertRaises(ToolValidationError): validate_parameters(p)
        actual = candidate_actual('six_b', 16); actual['bar_count'] = 8
        with self.assertRaises(ToolValidationError): validate_actual(actual)
        actual = candidate_actual('six_b', 16); actual['crosstie_axes'] = ['h', 'h']
        with self.assertRaises(ToolValidationError): validate_actual(actual)


class LayoutToolTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.output = Path(self.tmp.name)
        self.store = ColumnLayoutStore(self.output / 'column-layout-designs')
        self.design = ColumnLayoutDesignTool(self.store)
        self.check = ColumnLayoutCheckTool(self.store)

    def tearDown(self): self.tmp.cleanup()

    def test_reference_isolation_repeated_runs_and_actual_check(self):
        request = envelope('design_column_layouts', parameters(), 'LAYOUT-TEST')
        one, two = self.design.execute(request), self.design.execute(request)
        self.assertTrue(one.success, one.errors)
        self.assertTrue(two.success, two.errors)
        ref = one.result['design_result_ref']
        self.assertNotEqual(ref, two.result['design_result_ref'])
        checked = self.check.execute(envelope('check_column_layouts', {'design_result_ref': ref}, 'LAYOUT-TEST'))
        self.assertTrue(checked.success, checked.errors)
        self.assertEqual(checked.result['actual'], one.result['selected']['actual'])
        self.assertFalse(self.check.execute(envelope('check_column_layouts', {'design_result_ref': ref}, 'OTHER')).success)
        for wrong in ('column-' + 'a'*32, 'column-set-' + 'a'*32, '../bad'):
            self.assertFalse(self.check.execute(envelope('check_column_layouts', {'design_result_ref': wrong}, 'LAYOUT-TEST')).success)

    def test_snapshot_tamper_even_with_rehashed_envelope(self):
        result = self.design.execute(envelope('design_column_layouts', parameters(), 'LAYOUT-TEST'))
        ref = result.result['design_result_ref']
        path = self.store.root / (ref + '.json')
        data = json.loads(path.read_text(encoding='utf-8'))
        report = data['design']['result']
        report['selected']['combination_results'][0]['report']['faces'][0]['area_mm2'] += 1
        data['design']['metadata']['column_layout_sha256'] = canonical_hash({k:v for k,v in report.items() if k!='design_result_ref'})
        data['checksum'] = canonical_hash({k:v for k,v in data.items() if k!='checksum'})
        path.write_text(json.dumps(data), encoding='utf-8')
        with self.assertRaises(ColumnLayoutReferenceError): self.store.load(ref, project_id='LAYOUT-TEST')

    def test_check_rejects_swapped_actual_dropped_groups_and_unverified_reference(self):
        p = parameters()
        actual = candidate_actual('eight_perimeter', 14)
        for mutation in ('swap', 'drop', 'reference'):
            r = check_column_layouts(p, actual)
            if mutation == 'swap': r = check_column_layouts(p, candidate_actual('eight_perimeter', 16))
            elif mutation == 'drop': r['combination_results'].pop()
            else: r['design_result_ref'] = 'column-layout-'+'a'*32
            with patch('tools.column.layout_tools.check_column_layouts', return_value=r):
                checked = self.check.execute(envelope('check_column_layouts', {**p, 'actual': actual}, 'LAYOUT-TEST'))
            self.assertFalse(checked.success)
            self.assertEqual(checked.errors[0]['code'], 'column_layouts_check_invalid')

    def test_design_rejects_unauthorized_prefix_and_preserves_fail_output(self):
        p = parameters(layouts=['six_b'])
        failed = self.design.execute(envelope('design_column_layouts', p, 'LAYOUT-TEST'))
        self.assertFalse(failed.success)
        self.assertEqual(len(failed.result['attempts']), 8)
        self.assertFalse(self.store.root.exists())
        r = design_column_layouts(parameters())
        r['attempts'].pop(0)
        with self.assertRaises(ValueError): validate_design_semantics(r)

    def test_missing_and_cross_project_references_never_recompute_design(self):
        with patch('tools.column.layout_tools.design_column_layouts', side_effect=AssertionError('no redesign')):
            checked = self.check.execute(envelope('check_column_layouts',
                {'design_result_ref': 'column-layout-' + 'a'*32}, 'LAYOUT-TEST'))
        self.assertFalse(checked.success)
        self.assertEqual(checked.errors[0]['code'], 'invalid_column_layouts_reference')

    def test_controller_workflow_plugins_no_side_effects_and_failed_design_stops(self):
        before = (ROOT/'agent/controller.py').read_bytes()
        with patch('tools.column.layout_calculation.check_column', side_effect=AssertionError('load must not compute')):
            catalog = load_plugins(ROOT/'plugins', PluginContext(self.output))
        self.assertIn('design_floor_system', {t['name'] for t in catalog.registry.list_tools()})
        snapshot = run_request(envelope('design_column_layouts', parameters(), 'LAYOUT-TEST'), self.output)
        self.assertTrue(snapshot['success'], snapshot['errors'])
        self.assertEqual(snapshot['steps'], {'parse': 'completed', 'design': 'completed', 'check': 'completed'})
        failed = run_request(envelope('design_column_layouts', parameters(layouts=['six_b']), 'LAYOUT-TEST'), self.output)
        self.assertFalse(failed['success'])
        self.assertEqual(failed['steps']['check'], 'skipped')
        self.assertEqual(before, (ROOT/'agent/controller.py').read_bytes())

    def test_cli_examples_and_strict_json(self):
        for name, code, mode in [('four', 0, False), ('six-b', 0, False), ('six-h', 0, False),
                ('eight', 0, False), ('check-fail', 1, True), ('ties-fail', 1, True), ('design-fail', 1, False)]:
            command = [sys.executable, '-m', 'examples.column_layouts', '--request-file',
                str(ROOT/f'demos/column-layouts-{name}.json'), '--output-root', str(self.output)]
            if mode: command.append('--tool-only')
            proc = subprocess.run(command, cwd=ROOT, capture_output=True, timeout=60)
            self.assertEqual(proc.returncode, code, proc.stderr)
            snapshot = json.loads(proc.stdout.decode('utf-8'))
            self.assertEqual(snapshot['success'], code == 0)
        invalid = self.output / 'invalid.json'
        invalid.write_text('{"project_id":"A","project_id":"B"}', encoding='utf-8')
        proc = subprocess.run([sys.executable, '-m', 'examples.column_layouts', '--request-file', str(invalid)],
            cwd=ROOT, capture_output=True, timeout=30)
        self.assertEqual(proc.returncode, 1)
        self.assertEqual(json.loads(proc.stdout.decode('utf-8'))['status'], 'invalid_input')


if __name__ == '__main__': unittest.main()
